disp('Diode')
disp(' ')
disp('De eerste 4 reeksen hadden de normale schakeling,')
disp('de 5de had dde diode omgedraaid + 6de reeks als referentie.')
disp('De laatste (7de) heeft de diode en weerstand gewisseld van plaats.')
disp(' ')
disp(' ')
disp('Groen')
disp(' ')
disp('De eerste 3 reeksen hebben de LED juist geschakeld,')
disp('de 4de reeks heeft de diode omgedraaid.')
disp(' ')
disp(' ')
disp('Geel')
disp(' ')
disp('Drie normale reeksen met de gele LED')
disp(' ')
disp(' ')
disp('Gloeilamp')
disp(' ')
disp('Enkele normale reeksen met een gloeilamp i.p.v. diode/LED')
disp(' ')
disp(' ')
disp('DiodeGloei')
disp(' ')
disp('Deze had de gloeilamp als weerstand voor de diode')
disp('(in essentie niets anders dan een weerstand van 100 Ohm)')
disp(' ')
disp(' ')
disp('LDR')
disp(' ')
disp('De normale diode met een LDR -> lichtsafhankelijke weerstand.')

